version: '3.8'
services:
  minecraft:
    build: ./
    command: java -jar /var/minecraft/mohist-1.12.2-113-server.jar nogui
    # command: /bin/ls -lh /var/minecraft/mohist-1.12.2-113-server.jar
    ports:
      - 25565:25565
    volumes:
      - /home/neso/.minecraft/server:/var/minecraft