version: '3.8'
services:
  minecraft:
    build: ./
    command: /usr/bin/java -jar /var/minecraft/server/mohist-1.12.2-113-server.jar nogui
    # command: /bin/ls /var/minecraft -alsh
    ports:
      - 25565:25565
    volumes:
      - /home/neso/.minecraft/server:/var/minecraft