version: '3.6'
services:
  minecraft:
    build: ./docker/minecraft
    command: java -Xmx8G -jar mohist-1.12.2-113-server.jar nogui
    ports:
      - 25565:25565
    volumes:
      - /home/neso/.minecraft/server/:$HOME/.minecraft