version: '3.6'
services:
  minecraft:
    build: ./
    command: java -jar /home/neso/.minecraft/server/mohist-1.12.2-113-server.jar nogui
    ports:
      - 25565:25565
    volumes:
      - /home/neso/.minecraft/server:$HOME/.minecraft